/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OrganogramaRouteImport } from './routes/organograma'
import { Route as EstrategiaDigitalRouteImport } from './routes/estrategia-digital'
import { Route as IndexRouteImport } from './routes/index'

const OrganogramaRoute = OrganogramaRouteImport.update({
  id: '/organograma',
  path: '/organograma',
  getParentRoute: () => rootRouteImport,
} as any)
const EstrategiaDigitalRoute = EstrategiaDigitalRouteImport.update({
  id: '/estrategia-digital',
  path: '/estrategia-digital',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/estrategia-digital': typeof EstrategiaDigitalRoute
  '/organograma': typeof OrganogramaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/estrategia-digital': typeof EstrategiaDigitalRoute
  '/organograma': typeof OrganogramaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/estrategia-digital': typeof EstrategiaDigitalRoute
  '/organograma': typeof OrganogramaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/estrategia-digital' | '/organograma'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/estrategia-digital' | '/organograma'
  id: '__root__' | '/' | '/estrategia-digital' | '/organograma'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EstrategiaDigitalRoute: typeof EstrategiaDigitalRoute
  OrganogramaRoute: typeof OrganogramaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/organograma': {
      id: '/organograma'
      path: '/organograma'
      fullPath: '/organograma'
      preLoaderRoute: typeof OrganogramaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estrategia-digital': {
      id: '/estrategia-digital'
      path: '/estrategia-digital'
      fullPath: '/estrategia-digital'
      preLoaderRoute: typeof EstrategiaDigitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EstrategiaDigitalRoute: EstrategiaDigitalRoute,
  OrganogramaRoute: OrganogramaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
