/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RedeSarelliRouteImport } from './routes/rede-sarelli'
import { Route as PlanejamentoRouteImport } from './routes/planejamento'
import { Route as OrganogramaRouteImport } from './routes/organograma'
import { Route as InteligenciaEleitoralRouteImport } from './routes/inteligencia-eleitoral'
import { Route as EstrategiaDigitalRouteImport } from './routes/estrategia-digital'
import { Route as IndexRouteImport } from './routes/index'

const RedeSarelliRoute = RedeSarelliRouteImport.update({
  id: '/rede-sarelli',
  path: '/rede-sarelli',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanejamentoRoute = PlanejamentoRouteImport.update({
  id: '/planejamento',
  path: '/planejamento',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganogramaRoute = OrganogramaRouteImport.update({
  id: '/organograma',
  path: '/organograma',
  getParentRoute: () => rootRouteImport,
} as any)
const InteligenciaEleitoralRoute = InteligenciaEleitoralRouteImport.update({
  id: '/inteligencia-eleitoral',
  path: '/inteligencia-eleitoral',
  getParentRoute: () => rootRouteImport,
} as any)
const EstrategiaDigitalRoute = EstrategiaDigitalRouteImport.update({
  id: '/estrategia-digital',
  path: '/estrategia-digital',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/estrategia-digital': typeof EstrategiaDigitalRoute
  '/inteligencia-eleitoral': typeof InteligenciaEleitoralRoute
  '/organograma': typeof OrganogramaRoute
  '/planejamento': typeof PlanejamentoRoute
  '/rede-sarelli': typeof RedeSarelliRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/estrategia-digital': typeof EstrategiaDigitalRoute
  '/inteligencia-eleitoral': typeof InteligenciaEleitoralRoute
  '/organograma': typeof OrganogramaRoute
  '/planejamento': typeof PlanejamentoRoute
  '/rede-sarelli': typeof RedeSarelliRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/estrategia-digital': typeof EstrategiaDigitalRoute
  '/inteligencia-eleitoral': typeof InteligenciaEleitoralRoute
  '/organograma': typeof OrganogramaRoute
  '/planejamento': typeof PlanejamentoRoute
  '/rede-sarelli': typeof RedeSarelliRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/estrategia-digital'
    | '/inteligencia-eleitoral'
    | '/organograma'
    | '/planejamento'
    | '/rede-sarelli'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/estrategia-digital'
    | '/inteligencia-eleitoral'
    | '/organograma'
    | '/planejamento'
    | '/rede-sarelli'
  id:
    | '__root__'
    | '/'
    | '/estrategia-digital'
    | '/inteligencia-eleitoral'
    | '/organograma'
    | '/planejamento'
    | '/rede-sarelli'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EstrategiaDigitalRoute: typeof EstrategiaDigitalRoute
  InteligenciaEleitoralRoute: typeof InteligenciaEleitoralRoute
  OrganogramaRoute: typeof OrganogramaRoute
  PlanejamentoRoute: typeof PlanejamentoRoute
  RedeSarelliRoute: typeof RedeSarelliRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rede-sarelli': {
      id: '/rede-sarelli'
      path: '/rede-sarelli'
      fullPath: '/rede-sarelli'
      preLoaderRoute: typeof RedeSarelliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planejamento': {
      id: '/planejamento'
      path: '/planejamento'
      fullPath: '/planejamento'
      preLoaderRoute: typeof PlanejamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organograma': {
      id: '/organograma'
      path: '/organograma'
      fullPath: '/organograma'
      preLoaderRoute: typeof OrganogramaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inteligencia-eleitoral': {
      id: '/inteligencia-eleitoral'
      path: '/inteligencia-eleitoral'
      fullPath: '/inteligencia-eleitoral'
      preLoaderRoute: typeof InteligenciaEleitoralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estrategia-digital': {
      id: '/estrategia-digital'
      path: '/estrategia-digital'
      fullPath: '/estrategia-digital'
      preLoaderRoute: typeof EstrategiaDigitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EstrategiaDigitalRoute: EstrategiaDigitalRoute,
  InteligenciaEleitoralRoute: InteligenciaEleitoralRoute,
  OrganogramaRoute: OrganogramaRoute,
  PlanejamentoRoute: PlanejamentoRoute,
  RedeSarelliRoute: RedeSarelliRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
